<?php
include_once('workers/setBDManager.php');
include_once('beans/Set.php');

session_start();

// Check if user is logged in
function isLoggedIn() {
    return isset($_SESSION['user_id']);
}

// Check if user is admin
function isAdmin() {
    return isset($_SESSION['role']) && $_SESSION['role'] === 'Administrator';
}

if (isset($_SERVER['REQUEST_METHOD'])) {
    $setBD = new SetBDManager();
    
    switch ($_SERVER['REQUEST_METHOD']) {
        case 'GET':
            // Return all sets in XML format
            echo $setBD->getInXML();
            break;
            
        case 'POST':
            if (!isAdmin()) {
                http_response_code(403);
                echo "Unauthorized";
                exit;
            }
            
            // Get POST data
            $data = json_decode(file_get_contents('php://input'), true);
            
            // Create new Set object
            $set = new Set(
                null,  // PK_Set will be generated by database
                $_SESSION['user_id'],
                $data['nom'],
                $data['cap_nom'],
                $data['tunic_nom'],
                $data['trousers_nom'],
                $data['description'],
                $data['effet'],
                $data['fk_cap_source'],
                $data['fk_tunic_source'],
                $data['fk_trousers_source'],
                $data['image_set'] ?? null
            );
            
            // Add the set
            $newId = $setBD->addSet($set);
            echo json_encode(['success' => true, 'id' => $newId]);
            break;
            
        case 'PUT':
            if (!isAdmin()) {
                http_response_code(403);
                echo "Unauthorized";
                exit;
            }
            
            // Get PUT data
            $data = json_decode(file_get_contents('php://input'), true);
            
            // Create Set object with existing ID
            $set = new Set(
                $data['pk_set'],
                $_SESSION['user_id'],
                $data['nom'],
                $data['cap_nom'],
                $data['tunic_nom'],
                $data['trousers_nom'],
                $data['description'],
                $data['effet'],
                $data['fk_cap_source'],
                $data['fk_tunic_source'],
                $data['fk_trousers_source'],
                $data['image_set'] ?? null
            );
            
            // Update the set
            $success = $setBD->updateSet($set);
            echo json_encode(['success' => $success]);
            break;
            
        case 'DELETE':
            if (!isAdmin()) {
                http_response_code(403);
                echo "Unauthorized";
                exit;
            }
            
            // Get set ID from URL parameter
            $pk_set = $_GET['id'] ?? null;
            if (!$pk_set) {
                http_response_code(400);
                echo "Set ID is required";
                exit;
            }
            
            // Delete the set
            $success = $setBD->deleteSet($pk_set);
            echo json_encode(['success' => $success]);
            break;
    }
}
?>